/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Novel Plus API
 * 小説共有プラットフォームのAPI仕様
 * OpenAPI spec version: 1.0.0
 */

export * from "./novel";
export * from "./novelCreate";
export * from "./novelDetail";
export * from "./novelSummary";
export * from "./novelUpdate";
export * from "./novelView";
