/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Novel Plus API
 * 小説共有プラットフォームのAPI仕様
 * OpenAPI spec version: 1.0.0
 */
import type { NovelStatus } from "../schemas-enums-common/novelStatus";
import type { NovelType } from "../schemas-enums-common/novelType";
import type { User } from "../schemas-user/user";
import type { Tag } from "../schemas-tag/tag";
import type { ChapterSummary } from "../schemas-chapter/chapterSummary";

export interface NovelDetail {
  /** */
  id?: number;
  /** */
  userId?: number;
  /** */
  title?: string;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  coverUrl?: string | null;
  /** */
  status?: NovelStatus;
  /** */
  type?: NovelType;
  /** */
  viewsCount?: number;
  /** */
  bookmarksCount?: number;
  /** @nullable */
  ratingAvg?: number | null;
  /** */
  ratingsCount?: number;
  /** */
  createdAt?: string;
  /** */
  updatedAt?: string;
  /** @nullable */
  lastChapterAt?: string | null;
  /** */
  author?: User;
  tags?: Tag[];
  chapters?: ChapterSummary[];
  isBookmarked?: boolean;
  /**
   * @minimum 0
   * @maximum 5
   */
  userRating?: number;
}
