/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Novel Plus API
 * 小説共有プラットフォームのAPI仕様
 * OpenAPI spec version: 1.0.0
 */
import type { NovelStatus } from "./schemas-enums-common/novelStatus";
import type { NovelType } from "./schemas-enums-common/novelType";
import type { SortOrder } from "./schemas-enums-common/sortOrder";

export type GetNovelsParams = {
  page?: number;
  limit?: number;
  /**
   * タイトルでの検索
   */
  search?: string;
  status?: NovelStatus;
  type?: NovelType;
  /**
   * タグIDの配列
   */
  tags?: number[];
  sort?: SortOrder;
};
