/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Novel Plus API
 * 小説共有プラットフォームのAPI仕様
 * OpenAPI spec version: 1.0.0
 */
import type { GetRankings200DataItem } from "./getRankings200DataItem";
import type { GetRankings200Meta } from "./getRankings200Meta";

export type GetRankings200 = {
  data?: GetRankings200DataItem[];
  meta?: GetRankings200Meta;
};
