/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Novel Plus API
 * 小説共有プラットフォームのAPI仕様
 * OpenAPI spec version: 1.0.0
 */
import type { RankingType } from "./schemas-enums-common/rankingType";
import type { RankingCategory } from "./schemas-enums-common/rankingCategory";

export type GetRankings200Meta = {
  type?: RankingType;
  category?: RankingCategory;
  calculatedAt?: string;
};
