/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Novel Plus API
 * 小説共有プラットフォームのAPI仕様
 * OpenAPI spec version: 1.0.0
 */
import type { TagCategory } from "./schemas-enums-common/tagCategory";
import type { SortType } from "./schemas-enums-common/sortType";

export type GetTagsParams = {
  category?: TagCategory;
  sort?: SortType;
  limit?: number;
};
