/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Novel Plus API
 * 小説共有プラットフォームのAPI仕様
 * OpenAPI spec version: 1.0.0
 */

export type GetUsersIdNovelsStatus =
  (typeof GetUsersIdNovelsStatus)[keyof typeof GetUsersIdNovelsStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetUsersIdNovelsStatus = {
  ONGOING: "ONGOING",
  COMPLETED: "COMPLETED",
} as const;
