/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Novel Plus API
 * 小説共有プラットフォームのAPI仕様
 * OpenAPI spec version: 1.0.0
 */

export type GetUsersParams = {
  page?: number;
  limit?: number;
  /**
   * ユーザー名や表示名での検索
   */
  search?: string;
};
