/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Novel Plus API
 * 小説共有プラットフォームのAPI仕様
 * OpenAPI spec version: 1.0.0
 */
import type { User } from "./schemas-user/user";
import type { PaginationMeta } from "./schemas-common/paginationMeta";

export type GetUsers200 = {
  data?: User[];
  meta?: PaginationMeta;
};
