/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Novel Plus API
 * 小説共有プラットフォームのAPI仕様
 * OpenAPI spec version: 1.0.0
 */

export interface Notification {
  /** */
  id?: number;
  /** */
  category?: string;
  /** */
  title?: string;
  /** */
  content?: string;
  /** @nullable */
  link?: string | null;
  /** */
  publishedAt?: string;
  /** */
  createdAt?: string;
  /** */
  updatedAt?: string;
}
