/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Novel Plus API
 * 小説共有プラットフォームのAPI仕様
 * OpenAPI spec version: 1.0.0
 */

export interface User {
  /** */
  id?: number;
  /** */
  username?: string;
  /** */
  email?: string;
  /** @nullable */
  displayName?: string | null;
  /** @nullable */
  profile?: string | null;
  /** */
  createdAt?: string;
  /** */
  updatedAt?: string;
  /** @nullable */
  lastLoginAt?: string | null;
}
