/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Novel Plus API
 * 小説共有プラットフォームのAPI仕様
 * OpenAPI spec version: 1.0.0
 */

export interface UserCreate {
  email: string;
  /**
   * @minLength 3
   * @maxLength 50
   */
  username: string;
  /** @minLength 8 */
  password: string;
  /** @maxLength 50 */
  displayName?: string;
}
