/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Novel Plus API
 * 小説共有プラットフォームのAPI仕様
 * OpenAPI spec version: 1.0.0
 */

/**
 * 小説の状態（連載中/完結済）
 */
export type NovelStatus = (typeof NovelStatus)[keyof typeof NovelStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NovelStatus = {
  ONGOING: "ONGOING",
  COMPLETED: "COMPLETED",
} as const;
