/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Novel Plus API
 * 小説共有プラットフォームのAPI仕様
 * OpenAPI spec version: 1.0.0
 */

/**
 * 小説の種別（短編/中編/長編）
 */
export type NovelType = (typeof NovelType)[keyof typeof NovelType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NovelType = {
  SHORT: "SHORT",
  MEDIUM: "MEDIUM",
  LONG: "LONG",
} as const;
