/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Novel Plus API
 * 小説共有プラットフォームのAPI仕様
 * OpenAPI spec version: 1.0.0
 */

/**
 * ランキングのカテゴリー（閲覧数/ブックマーク数/評価）
 */
export type RankingCategory =
  (typeof RankingCategory)[keyof typeof RankingCategory];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RankingCategory = {
  VIEWS: "VIEWS",
  BOOKMARKS: "BOOKMARKS",
  RATING: "RATING",
} as const;
