/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Novel Plus API
 * 小説共有プラットフォームのAPI仕様
 * OpenAPI spec version: 1.0.0
 */

/**
 * ランキングの種類（日間/週間/月間）
 */
export type RankingType = (typeof RankingType)[keyof typeof RankingType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RankingType = {
  DAILY: "DAILY",
  WEEKLY: "WEEKLY",
  MONTHLY: "MONTHLY",
} as const;
