/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Novel Plus API
 * 小説共有プラットフォームのAPI仕様
 * OpenAPI spec version: 1.0.0
 */

/**
 * ソート順（新着順/更新順/人気順/評価順）
 */
export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SortOrder = {
  NEWEST: "NEWEST",
  UPDATED: "UPDATED",
  POPULAR: "POPULAR",
  RATING: "RATING",
} as const;
