/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Novel Plus API
 * 小説共有プラットフォームのAPI仕様
 * OpenAPI spec version: 1.0.0
 */

/**
 * タグのカテゴリー（ジャンル/キーワード/状態/長さ）
 */
export type TagCategory = (typeof TagCategory)[keyof typeof TagCategory];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TagCategory = {
  GENRE: "GENRE",
  KEYWORD: "KEYWORD",
  STATUS: "STATUS",
  LENGTH: "LENGTH",
} as const;
