/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Novel Plus API
 * 小説共有プラットフォームのAPI仕様
 * OpenAPI spec version: 1.0.0
 */
import type { RankingType } from "../schemas-enums-common/rankingType";

export interface Ranking {
  /** */
  id?: number;
  /** */
  novelId?: number;
  /** */
  type?: RankingType;
  /** */
  rank?: number;
  /** */
  score?: number;
  /** */
  calculatedAt?: string;
}
