/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Novel Plus API
 * 小説共有プラットフォームのAPI仕様
 * OpenAPI spec version: 1.0.0
 */
import type { Novel } from "../schemas-novel/novel";
import type { PaginationMeta } from "../schemas-common/paginationMeta";
import type { Tag } from "../schemas-tag/tag";

export interface Schema {
  data?: Novel[];
  meta?: PaginationMeta;
  tag?: Tag;
}
